// Le 25 voci del protocollo APEX 5D, dal file SKILL-VISION_Valutazione_5P.html
// (Foglio 7, Roberto Feliciani): codice, area, domanda di valutazione e indice
// comportamentale con gli ancoraggi per 1, 5 e 10.

export type Item5p = { cod: string; area: string; q: string; low: string; mid: string; high: string }

export const ITEMS_5P: Item5p[] = [
  { cod: "A1", area: "Competenze tecniche", q: "In che misura il dipendente possiede e applica le competenze tecniche richieste dal suo ruolo?", low: "Gravi lacune tecniche che compromettono il lavoro", mid: "Competenze adeguate al ruolo", high: "Expertise riconosciuta internamente, citata come riferimento" },
  { cod: "A2", area: "Conoscenze di processo", q: "Quanto conosce i processi, le procedure e le policy aziendali rilevanti per la sua funzione?", low: "Non conosce processi base", mid: "Conosce i processi core, applica le procedure", high: "Ottimizza i processi, propone miglioramenti" },
  { cod: "A3", area: "Utilizzo di strumenti", q: "Con quale efficacia utilizza gli strumenti, i software e le tecnologie necessari al ruolo?", low: "Difficoltà frequenti con gli strumenti base", mid: "Uso corretto e autonomo degli strumenti standard", high: "Massimizza le funzionalità, forma i colleghi" },
  { cod: "A4", area: "Decisioni e comunicazione", q: "Quanto è efficace nel prendere decisioni fondate e nel comunicarle in modo chiaro?", low: "Decisioni imprecise, comunicazione confusa", mid: "Decisioni corrette su temi noti, comunicazione chiara", high: "Decisioni rapide anche in ambiguità, comunicazione persuasiva" },
  { cod: "A5", area: "Creazione e condivisione di conoscenza", q: "In che misura genera nuove conoscenze e le trasferisce al team?", low: "Non documenta, non condivide", mid: "Condivide se richiesto, documentazione sufficiente", high: "Crea sistematicamente knowledge base, mentoring spontaneo" },
  { cod: "B1", area: "Rispetto scadenze e obiettivi", q: "Con quale frequenza e affidabilità il dipendente rispetta le scadenze assegnate?", low: "Manca sistematicamente le scadenze", mid: "Rispetta le scadenze standard con promemoria", high: "Consegna sempre puntuale, anticipa i ritardi degli altri" },
  { cod: "B2", area: "Qualità del lavoro", q: "Quanto il lavoro prodotto soddisfa o supera gli standard qualitativi aziendali?", low: "Qualità nettamente sotto standard, errori frequenti", mid: "Qualità nella norma, revisioni occasionali", high: "Qualità eccellente, zero revisioni, modello per gli altri" },
  { cod: "B3", area: "Collaborazione agli obiettivi di team", q: "In che misura contribuisce attivamente al raggiungimento degli obiettivi collettivi?", low: "Lavora in modo isolato, non supporta il team", mid: "Collabora nei contesti richiesti", high: "Catalizzatore del team, supera il perimetro del suo ruolo" },
  { cod: "B4", area: "Autonomia operativa", q: "Quanto è capace di lavorare in autonomia senza richiedere supervisione continua?", low: "Richiede supervisione costante", mid: "Autonomo sui task ordinari", high: "Massima autonomia anche su task complessi o nuovi" },
  { cod: "B5", area: "Crescita e sviluppo professionale", q: "In che misura dimostra impegno concreto nel migliorare le proprie competenze?", low: "Nessuna iniziativa di sviluppo", mid: "Partecipa alle formazioni obbligatorie", high: "Auto-diretto, cerca attivamente sfide formative, applica le nuove competenze" },
  { cod: "C1", area: "Adattabilità ai cambiamenti", q: "Con quale efficacia si adatta a cambiamenti organizzativi, di ruolo o di processo?", low: "Resistenza attiva ai cambiamenti", mid: "Accetta i cambiamenti e si adatta con il tempo", high: "Embraces il cambiamento, supporta gli altri nella transizione" },
  { cod: "C2", area: "Gestione del carico e dello stress", q: "Come gestisce situazioni di elevato carico lavorativo o pressione?", low: "Blocco operativo sotto pressione", mid: "Mantiene produttività accettabile sotto stress", high: "Eccelle sotto pressione, mantiene qualità e supporta il team" },
  { cod: "C3", area: "Apprendimento continuo", q: "Con quale velocità e profondità acquisisce nuove competenze e procedure?", low: "Lentezza significativa nell'apprendere nuovi temi", mid: "Apprendimento nella norma, consolida nel tempo", high: "Apprendimento rapido e profondo, generalizza autonomamente" },
  { cod: "C4", area: "Problem solving e creatività", q: "Quanto è efficace nell'identificare problemi e trovare soluzioni innovative?", low: "Difficoltà a risolvere problemi non routinari", mid: "Risolve problemi standard con approccio strutturato", high: "Anticipa i problemi, propone soluzioni creative e scalabili" },
  { cod: "C5", area: "Flessibilità di ruolo", q: "In che misura è disponibile e capace di ricoprire funzioni diverse dal suo ruolo ordinario?", low: "Rigidità totale, rifiuta attività fuori perimetro", mid: "Disponibile se richiesto, adattamento parziale", high: "Alta versatilità, copre ruoli diversi con efficacia" },
  { cod: "D1", area: "Impegno e dedizione nel ruolo", q: "Quanto dimostra impegno costante e ownership delle proprie responsabilità?", low: "Disimpegno evidente, fa il minimo", mid: "Impegno regolare, responsabile dei propri compiti", high: "Ownership totale, va oltre il richiesto per garantire i risultati" },
  { cod: "D2", area: "Contributo agli obiettivi aziendali", q: "In che misura le sue azioni contribuiscono concretamente al raggiungimento degli obiettivi aziendali?", low: "Contributo marginale o non rilevabile", mid: "Contributo nella norma, allineato agli obiettivi", high: "Impatto diretto e misurabile sugli obiettivi strategici" },
  { cod: "D3", area: "Partecipazione attiva", q: "Con quale qualità partecipa alle riunioni, alle iniziative e ai progetti aziendali?", low: "Presenza passiva, non contribuisce", mid: "Partecipazione standard, porta il suo punto di vista", high: "Partecipazione proattiva, propone, sintetizza, fa avanzare le discussioni" },
  { cod: "D4", area: "Motivazione e orientamento alla missione", q: "Quanto mostra motivazione intrinseca e allineamento con la cultura e la missione aziendale?", low: "Distacco dalla missione aziendale, motivazione assente", mid: "Motivazione adeguata, allineamento di base", high: "Ambasciatore della cultura aziendale, ispira i colleghi" },
  { cod: "D5", area: "Relazioni interpersonali e clima", q: "Con quale efficacia costruisce relazioni positive e contribuisce a un clima lavorativo sano?", low: "Fonte di conflitti o tensioni nel team", mid: "Relazioni corrette, clima neutro", high: "Costruttore di fiducia, clima positivo, punto di riferimento relazionale" },
  { cod: "E1", area: "Ricezione e utilizzo del feedback", q: "Come utilizza il feedback ricevuto per modificare concretamente il proprio comportamento?", low: "Rigetto o ignoranza del feedback", mid: "Accetta il feedback e apporta alcune modifiche", high: "Integra immediatamente il feedback, misura i progressi, chiede follow-up" },
  { cod: "E2", area: "Capacità di autovalutazione", q: "Quanto è accurata e critica la sua percezione delle proprie aree di forza e di miglioramento?", low: "Autovalutazione distorta, scarsa consapevolezza", mid: "Consapevolezza parziale, identifica le aree macro", high: "Autovalutazione precisa, identifica sfumature, piano d'azione autonomo" },
  { cod: "E3", area: "Formazione e aggiornamento", q: "Con quale proattività partecipa ad attività formative e si mantiene aggiornato sul settore?", low: "Evita la formazione se non obbligatoria", mid: "Partecipa alla formazione proposta", high: "Cerca formazione autonomamente, condivide le learnings, propone nuovi temi" },
  { cod: "E4", area: "Adozione di nuove tecnologie", q: "Con quale velocità ed efficacia adotta nuove tecnologie e strumenti introdotti in azienda?", low: "Resistenza o difficoltà significativa con le novità tecnologiche", mid: "Adozione nei tempi standard", high: "Early adopter, ottimizza l'uso, supporta i colleghi nell'adozione" },
  { cod: "E5", area: "Obiettivi di sviluppo personale", q: "In che misura si pone obiettivi di crescita personale e professionale e lavora per raggiungerli?", low: "Nessun obiettivo di sviluppo dichiarato o perseguito", mid: "Obiettivi presenti, progressi parziali", high: "Obiettivi SMART, progressi documentati, allineati agli obiettivi aziendali" },
]
