import { AlertTriangle, Building2, CheckCircle2, IdCard, Loader2, Plus, ShieldAlert, XCircle } from 'lucide-react'
import { useEffect, useState } from 'react'

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { cn } from '@/lib/utils'
import { ApiError, getBackendUser } from '@/lib/api/client'
import { campaignsApi, cipApi, companiesApi, platformsApi } from '@/lib/api/endpoints'
import { useBackendSession } from '@/lib/api/useBackendSession'
import type { BackendCampaign, BackendCip, BackendCompany, BackendPlatform, BackendSellerCode } from '@/lib/api/types'
import { EmptyState } from '@/modules/recruiting/components/EmptyState'

const inputClass =
  'rounded-md border border-border bg-background px-2.5 py-1.5 text-[12.5px] text-foreground placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/50'
const primaryBtnClass =
  'inline-flex items-center gap-1.5 whitespace-nowrap rounded-full border border-primary/30 bg-primary/10 px-3.5 py-1.5 text-[12.5px] font-bold text-foreground transition-colors hover:bg-primary/20 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/50 disabled:cursor-not-allowed disabled:opacity-60'
const ghostBtnClass =
  'inline-flex items-center gap-1.5 whitespace-nowrap rounded-full border border-border px-3.5 py-1.5 text-[12.5px] font-bold text-muted-foreground transition-colors hover:border-ring hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/50 disabled:cursor-not-allowed disabled:opacity-60'

function apiErrorMessage(err: unknown): string {
  if (err instanceof ApiError) return err.network ? 'Impossibile contattare il server.' : err.message
  return err instanceof Error ? err.message : 'Errore sconosciuto'
}

type OwnerType = 'PLATFORM' | 'COMPANY' | 'CAMPAIGN'

// Phase 33 §2 — CIP admin UI. Every action here maps 1:1 to a real backend
// endpoint (Phase 30 §6, extended this phase only with the missing LIST
// read — see backend/src/modules/cip/routes.ts's own comment on why that
// was added). Deliberately does NOT add an automatic/triggered generation
// path anywhere (OD-1's generation trigger stays unresolved) — every CIP
// here is generated by an explicit, visible click.
export default function CipAdminPage() {
  // RecruitingLayout already calls useBackendSession() once to establish
  // the bridge (lib/api/authBridge.ts), but that state lives in the LAYOUT
  // component, not here — React Router's <Outlet/> does not re-render a
  // route's own element just because the layout around it re-renders (the
  // element reference from context is unchanged), so a role check taken
  // from a one-time getBackendUser() read at THIS component's first render
  // would stay frozen at "not signed in yet" forever, even after the
  // bridge succeeds a moment later. Calling the hook again here is cheap
  // (ensureBackendSession() is already deduped/idempotent) and gives this
  // component its own state that actually triggers a re-render once the
  // session resolves — found via direct testing (a fresh navigation to
  // this route always showed the access-denied gate, even for a real
  // platform admin), not a hypothetical.
  const backend = useBackendSession()
  const isPlatformAdmin = getBackendUser()?.role === 'PLATFORM_ADMIN'

  const [sellerCodes, setSellerCodes] = useState<BackendSellerCode[]>([])
  const [platforms, setPlatforms] = useState<BackendPlatform[]>([])
  const [companies, setCompanies] = useState<BackendCompany[]>([])
  const [campaigns, setCampaigns] = useState<BackendCampaign[]>([])
  const [cips, setCips] = useState<BackendCip[]>([])
  const [loadError, setLoadError] = useState('')

  const [ownerType, setOwnerType] = useState<OwnerType>('PLATFORM')
  const [ownerId, setOwnerId] = useState('')
  const [sellerCodeId, setSellerCodeId] = useState('')
  const [generating, setGenerating] = useState(false)
  const [actionError, setActionError] = useState('')
  const [voidReason, setVoidReason] = useState<Record<string, string>>({})
  const [voidingId, setVoidingId] = useState<string | null>(null)

  const [newSellerCode, setNewSellerCode] = useState('')
  const [newSellerLabel, setNewSellerLabel] = useState('')

  useEffect(() => {
    if (backend.status !== 'connected' || !isPlatformAdmin) return
    let cancelled = false
    Promise.all([cipApi.listSellerCodes(), platformsApi.list(), companiesApi.list(), campaignsApi.list(), cipApi.list()])
      .then(([sc, pl, co, ca, allCips]) => {
        if (cancelled) return
        setSellerCodes(sc)
        setPlatforms(pl)
        setCompanies(co)
        setCampaigns(ca)
        setCips(allCips)
      })
      .catch((err) => !cancelled && setLoadError(apiErrorMessage(err)))
    return () => {
      cancelled = true
    }
  }, [backend.status, isPlatformAdmin])

  async function refreshCips() {
    try {
      setCips(await cipApi.list())
    } catch (err) {
      setLoadError(apiErrorMessage(err))
    }
  }

  async function handleGenerate() {
    if (generating || !ownerId || !sellerCodeId) return
    setGenerating(true)
    setActionError('')
    try {
      await cipApi.generate({ ownerType, ownerId, sellerCodeId })
      setOwnerId('')
      await refreshCips()
    } catch (err) {
      setActionError(apiErrorMessage(err))
    } finally {
      setGenerating(false)
    }
  }

  async function handleVoid(id: string) {
    const reason = (voidReason[id] || '').trim()
    if (!reason) {
      setActionError('Inserisci un motivo per annullare questo CIP.')
      return
    }
    setVoidingId(id)
    setActionError('')
    try {
      await cipApi.void(id, reason)
      setVoidReason((prev) => ({ ...prev, [id]: '' }))
      await refreshCips()
    } catch (err) {
      setActionError(apiErrorMessage(err))
    } finally {
      setVoidingId(null)
    }
  }

  async function handleCreateSellerCode() {
    if (!newSellerCode.trim() || !newSellerLabel.trim()) return
    setActionError('')
    try {
      await cipApi.createSellerCode(newSellerCode.trim().toUpperCase(), newSellerLabel.trim())
      setNewSellerCode('')
      setNewSellerLabel('')
      setSellerCodes(await cipApi.listSellerCodes())
    } catch (err) {
      setActionError(apiErrorMessage(err))
    }
  }

  const ownerOptions = ownerType === 'PLATFORM' ? platforms.map((p) => ({ id: p.id, label: p.name })) : ownerType === 'COMPANY' ? companies.map((c) => ({ id: c.id, label: c.name })) : campaigns.map((c) => ({ id: c.id, label: c.name }))

  if (backend.status === 'checking') {
    return (
      <div className="flex flex-col gap-4">
        <PageHeader />
        <div className="flex items-center gap-2 py-6 text-[13px] text-muted-foreground">
          <Loader2 className="size-4 shrink-0 animate-spin" aria-hidden="true" />
          Verifica sessione…
        </div>
      </div>
    )
  }

  if (!isPlatformAdmin) {
    return (
      <div className="flex flex-col gap-4">
        <PageHeader />
        <Card className="p-6">
          <EmptyState icon={ShieldAlert} text="Amministrazione CIP riservata ai platform admin. Il backend rifiuta comunque ogni richiesta da un account senza questo ruolo, indipendentemente da questa schermata." />
        </Card>
      </div>
    )
  }

  return (
    <div className="flex flex-col gap-4">
      <PageHeader />

      {loadError && <ErrorBanner message={loadError} />}

      <Card className="p-6">
        <CardHeader className="p-0 pb-3">
          <CardTitle className="flex items-center gap-1.5 text-sm">
            <Building2 className="size-4 shrink-0 text-muted-foreground" aria-hidden="true" />
            Codici venditore (Seller Code)
          </CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          <div className="flex flex-wrap gap-2">
            {sellerCodes.map((s) => (
              <span key={s.id} className="rounded-full border border-border px-2.5 py-1 text-[11.5px] font-semibold text-muted-foreground">
                {s.code} — {s.label}
              </span>
            ))}
            {!sellerCodes.length && <span className="text-[12px] text-muted-foreground">Nessun codice venditore ancora configurato.</span>}
          </div>
          <div className="mt-3 flex flex-wrap items-center gap-2">
            <input value={newSellerCode} onChange={(e) => setNewSellerCode(e.target.value)} placeholder="Codice (es. VR)" maxLength={8} className={cn(inputClass, 'w-[110px]')} />
            <input value={newSellerLabel} onChange={(e) => setNewSellerLabel(e.target.value)} placeholder="Etichetta" className={cn(inputClass, 'w-[220px]')} />
            <button type="button" onClick={handleCreateSellerCode} disabled={!newSellerCode.trim() || !newSellerLabel.trim()} className={primaryBtnClass}>
              <Plus className="size-3.5 shrink-0" aria-hidden="true" />
              Aggiungi
            </button>
          </div>
        </CardContent>
      </Card>

      <Card className="p-6">
        <CardHeader className="p-0 pb-3">
          <CardTitle className="flex items-center gap-1.5 text-sm">
            <IdCard className="size-4 shrink-0 text-muted-foreground" aria-hidden="true" />
            Genera nuovo CIP
          </CardTitle>
          <p className="mt-0.5 text-[11.5px] font-normal text-muted-foreground">
            Azione esplicita — nessuna generazione automatica esiste in questa build (il trigger automatico è una decisione di Roberto ancora da
            confermare, OD-1).
          </p>
        </CardHeader>
        <CardContent className="p-0">
          <div className="flex flex-wrap items-center gap-2">
            <select
              value={ownerType}
              onChange={(e) => {
                setOwnerType(e.target.value as OwnerType)
                setOwnerId('')
              }}
              className={inputClass}
            >
              <option value="PLATFORM">Platform</option>
              <option value="COMPANY">Company</option>
              <option value="CAMPAIGN">Campaign</option>
            </select>
            <select value={ownerId} onChange={(e) => setOwnerId(e.target.value)} className={cn(inputClass, 'min-w-[200px]')}>
              <option value="">{ownerOptions.length ? 'Seleziona…' : '(nessuno disponibile)'}</option>
              {ownerOptions.map((o) => (
                <option key={o.id} value={o.id}>
                  {o.label}
                </option>
              ))}
            </select>
            <select value={sellerCodeId} onChange={(e) => setSellerCodeId(e.target.value)} className={inputClass}>
              <option value="">Codice venditore…</option>
              {sellerCodes.map((s) => (
                <option key={s.id} value={s.id}>
                  {s.code}
                </option>
              ))}
            </select>
            <button type="button" onClick={handleGenerate} disabled={generating || !ownerId || !sellerCodeId} className={primaryBtnClass}>
              {generating ? <Loader2 className="size-3.5 shrink-0 animate-spin" aria-hidden="true" /> : <Plus className="size-3.5 shrink-0" aria-hidden="true" />}
              Genera CIP
            </button>
          </div>
          {actionError && (
            <p className="mt-2 flex items-start gap-1.5 text-[12px] font-medium text-destructive">
              <AlertTriangle className="mt-0.5 size-3.5 shrink-0" aria-hidden="true" />
              {actionError}
            </p>
          )}
        </CardContent>
      </Card>

      <Card className="p-6">
        <CardHeader className="p-0 pb-3">
          <CardTitle className="text-sm">CIP esistenti — {cips.length}</CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          {!cips.length ? (
            <EmptyState icon={IdCard} text="Nessun CIP generato ancora." />
          ) : (
            <div className="flex flex-col">
              {cips.map((c) => (
                <div key={c.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-border py-3 last:border-0">
                  <div className="min-w-0">
                    <div className="flex items-center gap-2 font-mono text-[13.5px] font-semibold">
                      {c.code}
                      {c.status === 'ACTIVE' ? (
                        <span className="inline-flex items-center gap-1 rounded-full bg-success/12 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-success">
                          <CheckCircle2 className="size-3 shrink-0" aria-hidden="true" />
                          Attivo
                        </span>
                      ) : (
                        <span className="inline-flex items-center gap-1 rounded-full bg-destructive/12 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-destructive">
                          <XCircle className="size-3 shrink-0" aria-hidden="true" />
                          Annullato
                        </span>
                      )}
                    </div>
                    <div className="mt-0.5 text-[11px] text-muted-foreground">
                      {c.ownerType} · anno 20{c.year2} · mese {String(c.month2).padStart(2, '0')} · sequenza {c.sequence} · venditore{' '}
                      {c.sellerCode?.code || '—'}
                      {c.status === 'VOIDED' && c.voidReason && <> · motivo: {c.voidReason}</>}
                    </div>
                  </div>
                  {c.status === 'ACTIVE' && (
                    <div className="flex shrink-0 items-center gap-2">
                      <input
                        value={voidReason[c.id] || ''}
                        onChange={(e) => setVoidReason((prev) => ({ ...prev, [c.id]: e.target.value }))}
                        placeholder="Motivo annullamento"
                        className={cn(inputClass, 'w-[180px]')}
                      />
                      <button type="button" onClick={() => handleVoid(c.id)} disabled={voidingId === c.id} className={ghostBtnClass}>
                        {voidingId === c.id ? <Loader2 className="size-3.5 shrink-0 animate-spin" aria-hidden="true" /> : null}
                        Annulla
                      </button>
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}

function PageHeader() {
  return (
    <div className="flex items-center gap-4">
      <div className="grid size-11 shrink-0 place-items-center rounded-full bg-secondary">
        <IdCard className="size-[22px] text-muted-foreground" aria-hidden="true" />
      </div>
      <div>
        <h2 className="text-lg font-semibold tracking-tight">Amministrazione CIP</h2>
        <p className="max-w-[70ch] text-[13px] text-muted-foreground">
          Codice Identificativo Piattaforma — generazione esplicita, annullamento/riemissione. Nessun trigger automatico (OD-1 non risolto).
        </p>
      </div>
    </div>
  )
}

function ErrorBanner({ message }: { message: string }) {
  return (
    <p className="flex items-start gap-1.5 rounded-md border border-destructive/30 bg-destructive/10 px-3.5 py-2.5 text-[12.5px] font-medium text-destructive">
      <AlertTriangle className="mt-0.5 size-3.5 shrink-0" aria-hidden="true" />
      {message}
    </p>
  )
}
