import { PageHeader } from '@/components/patterns/PageHeader'
import { AlertTriangle, Building2, CheckCircle2, IdCard, Loader2, Plus, ShieldAlert, XCircle } from 'lucide-react'
import { useEffect, useState } from 'react'

import { LoadingState } from '@/components/patterns/LoadingState'
import { InlineAlert } from '@/components/patterns/InlineAlert'
import { SelectField } from '@/components/patterns/SelectField'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import { buttonVariants } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { ApiError, getBackendUser } from '@/lib/api/client'
import { campaignsApi, cipApi, companiesApi, platformsApi } from '@/lib/api/endpoints'
import { useBackendSession } from '@/lib/api/useBackendSession'
import type { BackendCampaign, BackendCip, BackendCompany, BackendPlatform, BackendSellerCode } from '@/lib/api/types'
import { EmptyState } from '@/components/patterns/EmptyState'

// Was a locally hand-rolled className string (11+ near-duplicate copies of
// this same recipe existed across Recruiting, each drifted slightly in
// padding/font-size) — now the same buttonVariants() the shared <Button>
// component itself uses, so every "primary"/"ghost" action button in the
// app renders from one definition instead of N slightly-different copies.
const primaryBtnClass = buttonVariants({ size: 'sm' })
const ghostBtnClass = buttonVariants({ variant: 'outline', size: 'sm' })

function apiErrorMessage(err: unknown): string {
  if (err instanceof ApiError) return err.network ? 'Impossibile contattare il server.' : err.message
  return err instanceof Error ? err.message : 'Errore sconosciuto'
}

type OwnerType = 'PLATFORM' | 'COMPANY' | 'CAMPAIGN'

// Phase 33 §2 — CIP admin UI. Every action here maps 1:1 to a real backend
// endpoint (Phase 30 §6, extended this phase only with the missing LIST
// read — see backend/src/modules/cip/routes.ts's own comment on why that
// was added). Deliberately does NOT add an automatic/triggered generation
// path anywhere (OD-1's generation trigger stays unresolved) — every CIP
// here is generated by an explicit, visible click.
export default function CipAdminPage() {
  // RecruitingLayout already calls useBackendSession() once to establish
  // the bridge (lib/api/authBridge.ts), but that state lives in the LAYOUT
  // component, not here — React Router's <Outlet/> does not re-render a
  // route's own element just because the layout around it re-renders (the
  // element reference from context is unchanged), so a role check taken
  // from a one-time getBackendUser() read at THIS component's first render
  // would stay frozen at "not signed in yet" forever, even after the
  // bridge succeeds a moment later. Calling the hook again here is cheap
  // (ensureBackendSession() is already deduped/idempotent) and gives this
  // component its own state that actually triggers a re-render once the
  // session resolves — found via direct testing (a fresh navigation to
  // this route always showed the access-denied gate, even for a real
  // platform admin), not a hypothetical.
  const backend = useBackendSession()
  const isPlatformAdmin = getBackendUser()?.role === 'PLATFORM_ADMIN'

  const [sellerCodes, setSellerCodes] = useState<BackendSellerCode[]>([])
  const [platforms, setPlatforms] = useState<BackendPlatform[]>([])
  const [companies, setCompanies] = useState<BackendCompany[]>([])
  const [campaigns, setCampaigns] = useState<BackendCampaign[]>([])
  const [cips, setCips] = useState<BackendCip[]>([])
  const [loadError, setLoadError] = useState('')

  const [ownerType, setOwnerType] = useState<OwnerType>('PLATFORM')
  const [ownerId, setOwnerId] = useState('')
  const [sellerCodeId, setSellerCodeId] = useState('')
  const [referent, setReferent] = useState('')
  const [advisor, setAdvisor] = useState('')
  const [generating, setGenerating] = useState(false)
  const [actionError, setActionError] = useState('')
  const [voidReason, setVoidReason] = useState<Record<string, string>>({})
  const [voidingId, setVoidingId] = useState<string | null>(null)

  const [newSellerCode, setNewSellerCode] = useState('')
  const [newSellerLabel, setNewSellerLabel] = useState('')

  useEffect(() => {
    if (backend.status !== 'connected' || !isPlatformAdmin) return
    let cancelled = false
    Promise.all([cipApi.listSellerCodes(), platformsApi.list(), companiesApi.list(), campaignsApi.list(), cipApi.list()])
      .then(([sc, pl, co, ca, allCips]) => {
        if (cancelled) return
        setSellerCodes(sc)
        setPlatforms(pl)
        setCompanies(co)
        setCampaigns(ca)
        setCips(allCips)
      })
      .catch((err) => !cancelled && setLoadError(apiErrorMessage(err)))
    return () => {
      cancelled = true
    }
  }, [backend.status, isPlatformAdmin])

  async function refreshCips() {
    try {
      setCips(await cipApi.list())
    } catch (err) {
      setLoadError(apiErrorMessage(err))
    }
  }

  async function handleGenerate() {
    if (generating || !ownerId || !sellerCodeId) return
    setGenerating(true)
    setActionError('')
    try {
      await cipApi.generate({ ownerType, ownerId, sellerCodeId, referent: referent.trim() || undefined, advisor: advisor.trim() || undefined })
      setOwnerId('')
      setReferent('')
      setAdvisor('')
      await refreshCips()
    } catch (err) {
      setActionError(apiErrorMessage(err))
    } finally {
      setGenerating(false)
    }
  }

  async function handleVoid(id: string) {
    const reason = (voidReason[id] || '').trim()
    if (!reason) {
      setActionError('Inserisci un motivo per annullare questo CIP.')
      return
    }
    setVoidingId(id)
    setActionError('')
    try {
      await cipApi.void(id, reason)
      setVoidReason((prev) => ({ ...prev, [id]: '' }))
      await refreshCips()
    } catch (err) {
      setActionError(apiErrorMessage(err))
    } finally {
      setVoidingId(null)
    }
  }

  async function handleCreateSellerCode() {
    if (!newSellerCode.trim() || !newSellerLabel.trim()) return
    setActionError('')
    try {
      await cipApi.createSellerCode(newSellerCode.trim().toUpperCase(), newSellerLabel.trim())
      setNewSellerCode('')
      setNewSellerLabel('')
      setSellerCodes(await cipApi.listSellerCodes())
    } catch (err) {
      setActionError(apiErrorMessage(err))
    }
  }

  const ownerOptions = ownerType === 'PLATFORM' ? platforms.map((p) => ({ id: p.id, label: p.name })) : ownerType === 'COMPANY' ? companies.map((c) => ({ id: c.id, label: c.name })) : campaigns.map((c) => ({ id: c.id, label: c.name }))

  if (backend.status === 'checking') {
    return (
      <div className="flex flex-col gap-4">
        <CipHeader />
        <LoadingState label="Verifica sessione…" />
      </div>
    )
  }

  if (!isPlatformAdmin) {
    return (
      <div className="flex flex-col gap-4">
        <CipHeader />
        <Card>
          <EmptyState size="sm" icon={ShieldAlert} description="Amministrazione CIP riservata agli amministratori della piattaforma." />
        </Card>
      </div>
    )
  }

  return (
    <div className="flex flex-col gap-4">
      <CipHeader />

      {loadError && <InlineAlert>{loadError}</InlineAlert>}

      <Card>
        <CardHeader>
          <CardTitle>
            <Building2 className="size-4 shrink-0 text-muted-foreground" aria-hidden="true" />
            Codici venditore (Seller Code)
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex flex-wrap gap-2">
            {sellerCodes.map((s) => (
              <span key={s.id} className="rounded-full border border-border px-2.5 py-1 text-app-caption font-semibold text-muted-foreground">
                {s.code} — {s.label}
              </span>
            ))}
            {!sellerCodes.length && <span className="text-app-caption text-muted-foreground">Nessun codice venditore ancora configurato.</span>}
          </div>
          <div className="mt-3 flex flex-wrap items-center gap-2">
            <Input value={newSellerCode} onChange={(e) => setNewSellerCode(e.target.value)} placeholder="Codice (es. VR)" maxLength={8} size="sm" className="w-28" />
            <Input value={newSellerLabel} onChange={(e) => setNewSellerLabel(e.target.value)} placeholder="Etichetta" size="sm" className="w-56" />
            <button type="button" onClick={handleCreateSellerCode} disabled={!newSellerCode.trim() || !newSellerLabel.trim()} className={primaryBtnClass}>
              <Plus className="size-3.5 shrink-0" aria-hidden="true" />
              Aggiungi
            </button>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>
            <IdCard className="size-4 shrink-0 text-muted-foreground" aria-hidden="true" />
            Genera nuovo CIP
          </CardTitle>
          <p className="mt-0.5 text-app-caption font-normal text-muted-foreground">
            Azione esplicita — nessuna generazione automatica esiste in questa build (il trigger automatico è una decisione di Roberto ancora da
            confermare, OD-1).
          </p>
        </CardHeader>
        <CardContent>
          <div className="flex flex-wrap items-center gap-2">
            <SelectField
              value={ownerType}
              onValueChange={(v) => {
                setOwnerType(v as OwnerType)
                setOwnerId('')
              }}
              size="sm"
            >
              <option value="PLATFORM">Platform</option>
              <option value="COMPANY">Società</option>
              <option value="CAMPAIGN">Campaign</option>
            </SelectField>
            <SelectField value={ownerId} onValueChange={(v) => setOwnerId(v)} size="sm" className="min-w-52">
              <option value="">{ownerOptions.length ? 'Seleziona…' : '(nessuno disponibile)'}</option>
              {ownerOptions.map((o) => (
                <option key={o.id} value={o.id}>
                  {o.label}
                </option>
              ))}
            </SelectField>
            <SelectField value={sellerCodeId} onValueChange={(v) => setSellerCodeId(v)} size="sm">
              <option value="">Codice venditore…</option>
              {sellerCodes.map((s) => (
                <option key={s.id} value={s.id}>
                  {s.code}
                </option>
              ))}
            </SelectField>
            <Input value={referent} onChange={(e) => setReferent(e.target.value)} placeholder="Referente aziendale (cliente)" maxLength={120} size="sm" className="w-64" aria-label="Referente aziendale" />
            <Input value={advisor} onChange={(e) => setAdvisor(e.target.value)} placeholder="Advisor (fornitore)" maxLength={120} size="sm" className="w-56" aria-label="Advisor" />
            <button type="button" onClick={handleGenerate} disabled={generating || !ownerId || !sellerCodeId} className={primaryBtnClass}>
              {generating ? <Loader2 className="size-3.5 shrink-0 animate-spin" aria-hidden="true" /> : <Plus className="size-3.5 shrink-0" aria-hidden="true" />}
              Genera CIP
            </button>
          </div>
          {actionError && (
            <p className="mt-2 flex items-start gap-1.5 text-app-caption font-medium text-destructive">
              <AlertTriangle className="mt-0.5 size-3.5 shrink-0" aria-hidden="true" />
              {actionError}
            </p>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>CIP esistenti — {cips.length}</CardTitle>
        </CardHeader>
        <CardContent>
          {!cips.length ? (
            <EmptyState size="sm" icon={IdCard} description="Nessun CIP generato ancora." />
          ) : (
            <div className="flex flex-col">
              {cips.map((c) => (
                <div key={c.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-border py-3 last:border-0">
                  <div className="min-w-0">
                    <div className="flex items-center gap-2 font-mono text-app-small font-semibold">
                      {c.code}
                      {c.status === 'ACTIVE' ? (
                        <Badge tone="success">
                          <CheckCircle2 className="size-3 shrink-0" aria-hidden="true" />
                          Attivo
                        </Badge>
                      ) : (
                        <Badge tone="destructive">
                          <XCircle className="size-3 shrink-0" aria-hidden="true" />
                          Annullato
                        </Badge>
                      )}
                    </div>
                    <div className="mt-0.5 text-app-caption text-muted-foreground">
                      {c.ownerType} · anno 20{c.year2} · mese {String(c.month2).padStart(2, '0')} · sequenza {c.sequence} · venditore{' '}
                      {c.sellerCode?.code || '—'}
                      {c.status === 'VOIDED' && c.voidReason && <> · motivo: {c.voidReason}</>}
                    </div>
                  </div>
                  {c.status === 'ACTIVE' && (
                    <div className="flex shrink-0 items-center gap-2">
                      <Input
                        value={voidReason[c.id] || ''}
                        onChange={(e) => setVoidReason((prev) => ({ ...prev, [c.id]: e.target.value }))}
                        placeholder="Motivo annullamento"
                        size="sm" className="w-44"
 />
                      <button type="button" onClick={() => handleVoid(c.id)} disabled={voidingId === c.id} className={ghostBtnClass}>
                        {voidingId === c.id ? <Loader2 className="size-3.5 shrink-0 animate-spin" aria-hidden="true" /> : null}
                        Annulla
                      </button>
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}

function CipHeader() {
  return (
    <PageHeader
      level="page"
      className="mb-0"
      title="Amministrazione CIP"
      description="Codice Identificativo Piattaforma: si genera, si annulla e si riemette solo a mano, mai in automatico."
    />
  )
}

